//
//Copyright (c) 2025 Diagrid Inc.
//Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: proto/api/informer.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InformerEvent is sent by cron to the consumer to signal CRUD events of jobs.
type InformerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*InformerEvent_Put
	//	*InformerEvent_Delete
	//	*InformerEvent_DropAll
	Event isInformerEvent_Event `protobuf_oneof:"event"`
}

func (x *InformerEvent) Reset() {
	*x = InformerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_informer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformerEvent) ProtoMessage() {}

func (x *InformerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_informer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformerEvent.ProtoReflect.Descriptor instead.
func (*InformerEvent) Descriptor() ([]byte, []int) {
	return file_proto_api_informer_proto_rawDescGZIP(), []int{0}
}

func (m *InformerEvent) GetEvent() isInformerEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *InformerEvent) GetPut() *InformerEventJob {
	if x, ok := x.GetEvent().(*InformerEvent_Put); ok {
		return x.Put
	}
	return nil
}

func (x *InformerEvent) GetDelete() *InformerEventJob {
	if x, ok := x.GetEvent().(*InformerEvent_Delete); ok {
		return x.Delete
	}
	return nil
}

func (x *InformerEvent) GetDropAll() *InformerEventDropAll {
	if x, ok := x.GetEvent().(*InformerEvent_DropAll); ok {
		return x.DropAll
	}
	return nil
}

type isInformerEvent_Event interface {
	isInformerEvent_Event()
}

type InformerEvent_Put struct {
	Put *InformerEventJob `protobuf:"bytes,1,opt,name=put,proto3,oneof"`
}

type InformerEvent_Delete struct {
	Delete *InformerEventJob `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type InformerEvent_DropAll struct {
	DropAll *InformerEventDropAll `protobuf:"bytes,3,opt,name=drop_all,json=dropAll,proto3,oneof"`
}

func (*InformerEvent_Put) isInformerEvent_Event() {}

func (*InformerEvent_Delete) isInformerEvent_Event() {}

func (*InformerEvent_DropAll) isInformerEvent_Event() {}

// InformerEventJob is some event associated with a job.
type InformerEventJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the job that was put.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// metadata is the arbitrary metadata associated with the job.
	Metadata *anypb.Any `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// payload is the job payload.
	Payload *anypb.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *InformerEventJob) Reset() {
	*x = InformerEventJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_informer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformerEventJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformerEventJob) ProtoMessage() {}

func (x *InformerEventJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_informer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformerEventJob.ProtoReflect.Descriptor instead.
func (*InformerEventJob) Descriptor() ([]byte, []int) {
	return file_proto_api_informer_proto_rawDescGZIP(), []int{1}
}

func (x *InformerEventJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InformerEventJob) GetMetadata() *anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InformerEventJob) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

// InformerEventDropAll is sent when leadership election is occurring, or the
// Scheduler is shutting down, and therefore all jobs should be cleared.
type InformerEventDropAll struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InformerEventDropAll) Reset() {
	*x = InformerEventDropAll{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_informer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformerEventDropAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformerEventDropAll) ProtoMessage() {}

func (x *InformerEventDropAll) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_informer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformerEventDropAll.ProtoReflect.Descriptor instead.
func (*InformerEventDropAll) Descriptor() ([]byte, []int) {
	return file_proto_api_informer_proto_rawDescGZIP(), []int{2}
}

var File_proto_api_informer_proto protoreflect.FileDescriptor

var file_proto_api_informer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x0d, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x03,
	0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62,
	0x48, 0x00, 0x52, 0x03, 0x70, 0x75, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x48, 0x00,
	0x52, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x72, 0x6f, 0x70,
	0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x72,
	0x6f, 0x70, 0x41, 0x6c, 0x6c, 0x48, 0x00, 0x52, 0x07, 0x64, 0x72, 0x6f, 0x70, 0x41, 0x6c, 0x6c,
	0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x10, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x41, 0x6c, 0x6c, 0x42, 0x27, 0x5a, 0x25,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x61, 0x67, 0x72,
	0x69, 0x64, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x74, 0x63, 0x64, 0x2d, 0x63, 0x72, 0x6f,
	0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_informer_proto_rawDescOnce sync.Once
	file_proto_api_informer_proto_rawDescData = file_proto_api_informer_proto_rawDesc
)

func file_proto_api_informer_proto_rawDescGZIP() []byte {
	file_proto_api_informer_proto_rawDescOnce.Do(func() {
		file_proto_api_informer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_informer_proto_rawDescData)
	})
	return file_proto_api_informer_proto_rawDescData
}

var file_proto_api_informer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_api_informer_proto_goTypes = []interface{}{
	(*InformerEvent)(nil),        // 0: api.InformerEvent
	(*InformerEventJob)(nil),     // 1: api.InformerEventJob
	(*InformerEventDropAll)(nil), // 2: api.InformerEventDropAll
	(*anypb.Any)(nil),            // 3: google.protobuf.Any
}
var file_proto_api_informer_proto_depIdxs = []int32{
	1, // 0: api.InformerEvent.put:type_name -> api.InformerEventJob
	1, // 1: api.InformerEvent.delete:type_name -> api.InformerEventJob
	2, // 2: api.InformerEvent.drop_all:type_name -> api.InformerEventDropAll
	3, // 3: api.InformerEventJob.metadata:type_name -> google.protobuf.Any
	3, // 4: api.InformerEventJob.payload:type_name -> google.protobuf.Any
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_api_informer_proto_init() }
func file_proto_api_informer_proto_init() {
	if File_proto_api_informer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_informer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_informer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformerEventJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_informer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformerEventDropAll); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_api_informer_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*InformerEvent_Put)(nil),
		(*InformerEvent_Delete)(nil),
		(*InformerEvent_DropAll)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_informer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_informer_proto_goTypes,
		DependencyIndexes: file_proto_api_informer_proto_depIdxs,
		MessageInfos:      file_proto_api_informer_proto_msgTypes,
	}.Build()
	File_proto_api_informer_proto = out.File
	file_proto_api_informer_proto_rawDesc = nil
	file_proto_api_informer_proto_goTypes = nil
	file_proto_api_informer_proto_depIdxs = nil
}
