//
//Copyright (c) 2024 Diagrid Inc.
//Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.3
// source: proto/api/trigger.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TriggerResponseResult is indicates the state result from triggering the job
// by the consumer.
type TriggerResponseResult int32

const (
	// SUCCESS indicates that the job was successfully triggered and will be
	// ticked forward according to the schedule.
	TriggerResponseResult_SUCCESS TriggerResponseResult = 0
	// FAILED indicates that the job failed to trigger and is subject to the
	// FailurePolicy.
	TriggerResponseResult_FAILED TriggerResponseResult = 1
	// UNDELIVERABLE indicates that the job should be added to the staging queue
	// as the Job was undeliverable. Once the Job name prefix is marked as
	// deliverable, it will be immediately triggered.
	TriggerResponseResult_UNDELIVERABLE TriggerResponseResult = 2
)

// Enum value maps for TriggerResponseResult.
var (
	TriggerResponseResult_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILED",
		2: "UNDELIVERABLE",
	}
	TriggerResponseResult_value = map[string]int32{
		"SUCCESS":       0,
		"FAILED":        1,
		"UNDELIVERABLE": 2,
	}
)

func (x TriggerResponseResult) Enum() *TriggerResponseResult {
	p := new(TriggerResponseResult)
	*p = x
	return p
}

func (x TriggerResponseResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerResponseResult) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_api_trigger_proto_enumTypes[0].Descriptor()
}

func (TriggerResponseResult) Type() protoreflect.EnumType {
	return &file_proto_api_trigger_proto_enumTypes[0]
}

func (x TriggerResponseResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerResponseResult.Descriptor instead.
func (TriggerResponseResult) EnumDescriptor() ([]byte, []int) {
	return file_proto_api_trigger_proto_rawDescGZIP(), []int{0}
}

// TriggerRequest is the request sent to the caller when a job is triggered.
type TriggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the job that was triggered.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// metadata is the arbitrary metadata associated with the job.
	Metadata *anypb.Any `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// payload is the job payload.
	Payload *anypb.Any `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_trigger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_trigger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_proto_api_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriggerRequest) GetMetadata() *anypb.Any {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TriggerRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

// TriggerResponse is returned by the caller from a TriggerResponse. Signals
// whether the Job was successfully triggered, the trigger failed, or instead
// needs to be added to the staging queue due to impossible delivery.
type TriggerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// result is the result given by the consumer when trigging the Job.
	Result TriggerResponseResult `protobuf:"varint,1,opt,name=result,proto3,enum=api.TriggerResponseResult" json:"result,omitempty"`
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_api_trigger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_trigger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_proto_api_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerResponse) GetResult() TriggerResponseResult {
	if x != nil {
		return x.Result
	}
	return TriggerResponseResult_SUCCESS
}

var File_proto_api_trigger_proto protoreflect.FileDescriptor

var file_proto_api_trigger_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x19,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x0e, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x30, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x45, 0x0a, 0x0f, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x43, 0x0a, 0x15, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x55,
	0x4e, 0x44, 0x45, 0x4c, 0x49, 0x56, 0x45, 0x52, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x61,
	0x67, 0x72, 0x69, 0x64, 0x69, 0x6f, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x74, 0x63, 0x64, 0x2d, 0x63,
	0x72, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_api_trigger_proto_rawDescOnce sync.Once
	file_proto_api_trigger_proto_rawDescData = file_proto_api_trigger_proto_rawDesc
)

func file_proto_api_trigger_proto_rawDescGZIP() []byte {
	file_proto_api_trigger_proto_rawDescOnce.Do(func() {
		file_proto_api_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_api_trigger_proto_rawDescData)
	})
	return file_proto_api_trigger_proto_rawDescData
}

var file_proto_api_trigger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_api_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_api_trigger_proto_goTypes = []interface{}{
	(TriggerResponseResult)(0), // 0: api.TriggerResponseResult
	(*TriggerRequest)(nil),     // 1: api.TriggerRequest
	(*TriggerResponse)(nil),    // 2: api.TriggerResponse
	(*anypb.Any)(nil),          // 3: google.protobuf.Any
}
var file_proto_api_trigger_proto_depIdxs = []int32{
	3, // 0: api.TriggerRequest.metadata:type_name -> google.protobuf.Any
	3, // 1: api.TriggerRequest.payload:type_name -> google.protobuf.Any
	0, // 2: api.TriggerResponse.result:type_name -> api.TriggerResponseResult
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_api_trigger_proto_init() }
func file_proto_api_trigger_proto_init() {
	if File_proto_api_trigger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_api_trigger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_api_trigger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_api_trigger_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_trigger_proto_goTypes,
		DependencyIndexes: file_proto_api_trigger_proto_depIdxs,
		EnumInfos:         file_proto_api_trigger_proto_enumTypes,
		MessageInfos:      file_proto_api_trigger_proto_msgTypes,
	}.Build()
	File_proto_api_trigger_proto = out.File
	file_proto_api_trigger_proto_rawDesc = nil
	file_proto_api_trigger_proto_goTypes = nil
	file_proto_api_trigger_proto_depIdxs = nil
}
